# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/aptRepoUpdater.sh; fi'

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "IVHgLPobDjX9XJvmSBBnvb5TZx7RdT4oN1p3DUNhnIcLnh5JJSQR3/PIalgZkkIpqIrYAHX/xP/w8uylJ0YmfBya7vASX/kIPlvmner95x96BXKvOefpJ6YpCMbb8mRB9RNQd0ZN0Uto2I6dHPcLgcpuJ8kGzFVAHBi395kaYObySgiRo2zrFvO7ZcwxQ9Xy5eBbJBCL3vCiFJfCJ+bH3p8idPQWCCDBaRHFBPBiZyl0pH/H61cDIqhgx/Ga0RUFm8zobJ5QKsPTTBaneFyRzS9BewqdZozPHanM5ckMegYOoXwcOqILjWhtnMmoH66LEcJGybUVcSyrBUXyWTOQfYSdrv1prlh++3OieOl3Zy4cj15zuIn2xQQG3uUBtyudRXwmci/rNoKAgeM+nML6UiTwVF4kLNFoHU9WBNzamsxzApCvtQuzc90PXyVkAIOuEQbKs/TIX3LTOpzU13PELKnAJCgYIyvJabNDBS6aN6qHYxHRxf0eERB/GDY2E7k3zz1TlVBO3Fn5eP5zSWD3NhpPmplK+l7pwSqpXmNg+fzJhspD9A1/vEjVFmmi1jOgW0SNPAhgk95z2blxI5lVVzPVgSlmUTnHqHepHJbM1kB1DN4MKHC086f+vXwrBbxaqP5KD/klTrFQWayNsHZPQ1rKD0NHZdw3CFr2+bEBjpg="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      branch: master
