# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/aptRepoUpdater.sh; fi'

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "NsGyiDNJ09eeJykrVyR01+nCPjJyj17po5wCPAufsnZYIaAliYQ28jFyD6r16vo76RqGNGeKt2vG7kRYtp8OpQQfUdWbAs71+qu5ahoK6YedaMr7iRRxw+uWD9caSYCpJvRqIP1ojfJ6eEo/pk1lAzEaIf0rdQukkr/eKOjqAIExZdcTPLGqfYJmv938LSenjZl98Tql9+kzgiqkoxkAcN2NyIuQ5ldZB9x61SstGG59181ee3xW4HpoTfeUuBC1ZlI9aGKsDBzHgPypCdMDAiQdtCgyl7bTzseluwUyAIMmaJiM050+x6LN7DBIu6zywMnXbDbe2PCbkrLE362jAV+fRUyA4P+/HVsngXA11SS2sFzI3BVW8Mc6sDndKDsW6MWEu+QPTBCpUd8K33SX03sA/zBpf/n2DFHdaWt29FqJQNmVKjk5G0/BVjJ0CH6eoUBFL6/+fIfdoKmFiWWK0jdHC4bOz4PttZ4cOhW2YxWe2ENLBHs1rRaFq1rwdxer/pQkC6Tqbr5aTfUgzdrjTbov8cKR1sVlpbxW+O2SFustSMkSlAcp0ajZNZvbBR1za11CWNgr455YIyGGHwhsZdObhjJNLbR38NrRgND3qo/MZ02YfpNbxAazYe1/XRM1yvcvDDTljesHpdmN18j+HtzgAuu8l41JFfVaNfsYmXo="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      branch: master
