# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/aptRepoUpdater.sh; fi'

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "p1kOGPnb/58jFJiwsnffz1WOnMdzhBglbSUesYBBa0z7WxGnqpk9Oc6LbkqBCs0pdeJvEIWJ8OqiUPaI3BmQuQ5Yf2BBuRiCMOwT9zRJJ7M7uG2FPYtmH3bl4OnvHE++AKNqAOaP1m/FIPo1Ulsznu+yH6nby/f0zjuUYqF88iaUSGuzrvqLfkQCCnabi/YpVUR1xBIBcwvZI2rNPmarjL7Tl86UtXHcbBrND3XGrVc+X2nvkKnuzNwcADFAh9AenMoq/UrZsFZ5zdBcwMdEa5BR2RFMfZlVpJwULTQ/WaAOEq7hxX6M/eduqfnuEdvpNtcV34A2NpXjsVVLTIRTFx7HV51zAZwTHmwfO7I77zNAbVKV3DCNZswdCc0SngJN/p000K5Gq4GRCCOaotiKxhdwweXmGf2eE3TTrGM7GdXHDgd/XrTxaLuMWh25XaXplibESHHtOYHJ3oiTynDaUsp6wzwtOuNI3FYjVr7kXw2cmDsQodwodTEB83SHkjd3feMTBOhVQWJX+yNla1JV7kILkIYo7fwvCIGQmzlzIboGf0lzwJ4IPJIJLJuWWhHLyqQ3amutQphiXhENkhQNvFzWhTZH25gXY00VnzVMLwhlvroXEQcWxkHRHhn6Da3h2Y1rN/4MEzPAOw3f7bYVL7W/g9rKJ3tZsJOLQCDr/L4="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      branch: master
