language: generic
sudo: required

# command to install dependencies
# We don't have any dependencies yet!
#install:
#  - pip install -r requirements.txt

# command to run tests
script:
  - ./build.sh
notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC
