# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/aptRepoUpdater.sh; fi'

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "V0RHGMGHqbqgcdENKy9Vj++CkhrwKCXCGqHKO1RXacTQ026/ITWhFTb1X5aeUGNn+aNKCW1X30wxC+BglqMkhfWH/AQZdeVUfBEQlyWUBpEWIiny7mlQu76adn17RJ2nD9mtUTdAI2IUkqJdBS2gca49ugfj7sqRpaQy51Xl3pHWkH6C0ypidt4Y/fmB9LsZDs/ISSgHly8ol+o60sNQZ29lxsfHECiVYUIWAMNlqvI9jN/XxJt3dda8CCiwBx9b/k/zXZAiBDsX5/umlqEydkY3fSQiJUoZQMhg9/hmKwBEpUr1khTkCeQzO6nHezYEZzNIQj9UKfU2l01bMuOhp5nMS0KCrHFH7eP/sDt6X8J82T5mD8vu8EPZdSt7zioCnR1y2vWaBq5ztc+ptNGNO11vYqU5V8iuncSx1tGXbsdjuMAjrhfnCc2oUWPTP4+vR9kt++BrpC0grgNTuQ+h7gIBDiU0GDGu3VOwSt/XRRHcSlf+HWbI121y40gDWeaFl2WtFwRPn5al6SkVeu26EJLqJxxnrNgB10aN27LSIwL4Ll8mYfwiov+IsGCmU1TYWv7ANhhWuSU546eqH/HnIKLXZ/jeUT9zp6NpADR6XPF5PnVZOmZ3hnsVZyeNo/B45wm+duSj762ywT0G4cmEvhGnLj7P0Zv1UHDwCxro+Nc="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      branch: master
