language: python
sudo: required
python: "3.4"

# command to install dependencies
# We don't have any dependencies yet!
#install:
#  - pip install -r requirements.txt

# command to run tests
script:
  - bash ./build.sh

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC
